services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ingestor:
    build:
      context: .
      dockerfile: ingestor/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka

  example-service:
    build: 
      context: .
      dockerfile: example-service/Dockerfile
    environment: 
      PORT: "9092"
      KAFKA_BROKER: "kafka"
    ports:
     - "9093:9093"
    depends_on:
      - kafka

  simulation:
    build:
      context: ./simulation
      dockerfile: Dockerfile
    environment:
      - AM_I_IN_DOCKER=true
      - INGESTOR_URL=http://ingestor:8080/ingest
    depends_on:
      - ingestor

#   server:
#     build: 
#       context: .
#       dockerfile: ./cmd/server/Dockerfile
#     ports:
#      - "8080:8080"
#     environment:
#       DB_URL: ${DB_URL}
#     depends_on:
#      - postgres
#      - kafka

#   consumer:
#     build: 
#       context: .
#       dockerfile: ./cmd/consumer/Dockerfile
#     environment: 
#       PORT: "9092"
#       KAFKA_BROKER: "kafka"
#     ports:
#      - "9093:9093"
#     depends_on:
#       - kafka

#   postgres:
#     image: postgres:16
#     container_name: postgres
#     restart: always
#     environment:
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword
#       POSTGRES_DB: mydb
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:

